name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Use your correct region here

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p python-3.8 my-app --region us-east-1  # Replace with your app name and region
          eb deploy
