name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # This triggers the workflow only when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version for your app

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements file

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use the AWS Access Key ID from GitHub Secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use the AWS Secret Access Key from GitHub Secrets
        aws-region: 'us-east-1'  # Set your region here

    - name: Deploy to Elastic Beanstalk
      run: |
        pip install awsebcli  # Install Elastic Beanstalk CLI
        eb init -p python-3.8 project --region us-east-1  # Initialize Elastic Beanstalk app (replace 'project' with your app name)
        eb use Project-env-1  # Use the environment name
        eb deploy  # Deploy the app to Elastic Beanstalk

    - name: Clean up
      run: |
        echo "Deployment finished!"
