name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger only for changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use the checkout action to fetch your code

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1  # Configure AWS credentials for the workflow
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update to your AWS region if necessary

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli  # Install the Elastic Beanstalk CLI

      - name: Initialize Elastic Beanstalk application
        run: |
          eb init -p python-3.8 project --region us-east-1  # Replace 'project' with your app name
          eb use Project-env-1  # Use your environment name

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy  # Deploy your application to Elastic Beanstalk
